package io.github.xgl34222220.bichen;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.util.*;

public final class ProxyNetworkMatchActivity extends Activity {
    private SharedPreferences prefs; private ProxyUi u;
    private TextView enabledValue,statusValue,matchValue,unmatchValue,ssidValue,bssidValue,mobileValue;
    @Override public void onCreate(Bundle s){prefs=getSharedPreferences("bichen",MODE_PRIVATE);setTheme(ProxyUi.isDark(this)?R.style.AppThemeDark:R.style.AppTheme);super.onCreate(s);u=new ProxyUi(this);build();refresh();}
    private void build(){LinearLayout shell=u.col();u.window(shell);ScrollView scroll=new ScrollView(this);LinearLayout body=u.col();body.setPadding(u.dp(14),u.dp(18),u.dp(14),u.dp(34));scroll.addView(body);shell.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout top=u.row();top.setGravity(Gravity.CENTER_VERTICAL);top.addView(u.icon("back","返回",this::finish),new LinearLayout.LayoutParams(u.dp(46),u.dp(46)));TextView title=u.text("网络匹配",31,u.text,true);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.leftMargin=u.dp(8);top.addView(title,tp);body.addView(top);u.gap(body,16);TextView tip=u.text("持续监听默认网络。可按 Wi‑Fi SSID/BSSID 或移动数据匹配，并自动启动/停止 Root 代理。",12,u.muted,false);tip.setPadding(u.dp(8),0,u.dp(8),u.dp(12));body.addView(tip);LinearLayout c=u.card(body);c.setPadding(u.dp(18),0,u.dp(18),0);enabledValue=row(c,"启用网络匹配",this::toggleEnabled);u.separator(c);statusValue=row(c,"当前环境",this::evaluate);u.separator(c);matchValue=row(c,"匹配成功动作",()->chooseAction("networkMatchAction",true));u.separator(c);unmatchValue=row(c,"失配动作",()->chooseAction("networkUnmatchAction",false));LinearLayout r=u.card(body);r.setPadding(u.dp(18),0,u.dp(18),0);ssidValue=row(r,"Wi‑Fi SSID",()->editSet("networkMatchSsids","Wi‑Fi SSID","每行一个 SSID；留空表示不限"));u.separator(r);bssidValue=row(r,"Wi‑Fi BSSID",()->editSet("networkMatchBssids","Wi‑Fi BSSID","每行一个 BSSID；留空表示不限"));u.separator(r);mobileValue=row(r,"移动数据匹配",()->{prefs.edit().putBoolean("networkMatchMobile",!prefs.getBoolean("networkMatchMobile",false)).apply();refresh();evaluate();});setContentView(shell);shell.requestApplyInsets();}
    private TextView row(LinearLayout p,String label,Runnable a){LinearLayout r=u.row();r.setMinimumHeight(u.dp(70));r.setGravity(Gravity.CENTER_VERTICAL);r.setBackground(u.touch(android.graphics.Color.TRANSPARENT,14));r.addView(u.text(label,16.5f,u.text,true),new LinearLayout.LayoutParams(0,-2,1));TextView v=u.text("",14,u.muted,false);v.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);v.setMaxWidth(u.dp(210));v.setSingleLine(true);r.addView(v,new LinearLayout.LayoutParams(-2,-1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(u.dp(18),u.dp(18));cp.leftMargin=u.dp(7);r.addView(new IconView(this,"chevron",u.muted),cp);r.setOnClickListener(x->a.run());p.addView(r);return v;}
    private void toggleEnabled(){boolean n=!prefs.getBoolean("networkMatchEnabled",false);prefs.edit().putBoolean("networkMatchEnabled",n).apply();if(n){requestWifiPermission();startForegroundService(new Intent(this,ProxyNetworkMatchService.class).setAction("START"));}else stopService(new Intent(this,ProxyNetworkMatchService.class));refresh();}
    private void requestWifiPermission(){if(Build.VERSION.SDK_INT>=33){ArrayList<String> q=new ArrayList<>();if(checkSelfPermission(Manifest.permission.NEARBY_WIFI_DEVICES)!=PackageManager.PERMISSION_GRANTED)q.add(Manifest.permission.NEARBY_WIFI_DEVICES);if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)q.add(Manifest.permission.ACCESS_FINE_LOCATION);if(!q.isEmpty())requestPermissions(q.toArray(new String[0]),908);}else if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION},908);}
    private void chooseAction(String key,boolean match){String[] labels={"不操作","启动 Root 代理","停止 Root 代理"},values={"none","start","stop"};String cur=prefs.getString(key,match?"start":"none");int checked=Arrays.asList(values).indexOf(cur);new AlertDialog.Builder(this).setTitle(match?"匹配成功动作":"失配动作").setSingleChoiceItems(labels,Math.max(0,checked),(d,w)->{prefs.edit().putString(key,values[w]).apply();d.dismiss();refresh();evaluate();}).setNegativeButton("取消",null).show();}
    private Set<String> values(String key){Set<String>s=prefs.getStringSet(key,Collections.emptySet());return s==null?new TreeSet<>():new TreeSet<>(s);}
    private void editSet(String key,String title,String hint){EditText in=new EditText(this);in.setText(android.text.TextUtils.join("\n",values(key)));in.setHint(hint);in.setMinLines(5);FrameLayout wrap=new FrameLayout(this);int m=u.dp(20);wrap.setPadding(m,u.dp(4),m,0);wrap.addView(in,new FrameLayout.LayoutParams(-1,-2));new AlertDialog.Builder(this).setTitle(title).setMessage(hint).setView(wrap).setPositiveButton("保存",(d,w)->{TreeSet<String>out=new TreeSet<>();for(String x:in.getText().toString().split("[\\n,;]+")){String v=x.trim();if(!v.isEmpty())out.add(v);}prefs.edit().putStringSet(key,out).apply();refresh();evaluate();}).setNegativeButton("取消",null).show();}
    private String action(String key,String def){String v=prefs.getString(key,def);return "start".equals(v)?"启动代理":"stop".equals(v)?"停止代理":"不操作";}
    private void evaluate(){prefs.edit().putBoolean("networkMatchForceEval",true).apply();if(prefs.getBoolean("networkMatchEnabled",false))startForegroundService(new Intent(this,ProxyNetworkMatchService.class).setAction("EVAL"));new Handler(Looper.getMainLooper()).postDelayed(this::refresh,500);}
    private void refresh(){enabledValue.setText(prefs.getBoolean("networkMatchEnabled",false)?"开启":"关闭");statusValue.setText(prefs.getString("networkMatchLastEnvironment","点击刷新"));matchValue.setText(action("networkMatchAction","start"));unmatchValue.setText(action("networkUnmatchAction","none"));ssidValue.setText(values("networkMatchSsids").isEmpty()?"不限":values("networkMatchSsids").size()+" 个");bssidValue.setText(values("networkMatchBssids").isEmpty()?"不限":values("networkMatchBssids").size()+" 个");mobileValue.setText(prefs.getBoolean("networkMatchMobile",false)?"开启":"关闭");}
}
