package bichen.proxyuicheck;

import android.app.*;import android.content.*;import android.graphics.Bitmap;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;import java.lang.reflect.*;
/** Installed regression for the BoxProxy-style Root console and basic proxy configuration. */
public final class UiCheck extends Instrumentation{
 Context c;Activity a;int checks;StringBuilder output=new StringBuilder();
 void check(boolean ok,String name){if(!ok)throw new AssertionError(name);checks++;output.append("PASS ").append(name).append('\n');}
 Object invoke(Object o,String name,Class<?>[] t,Object...args)throws Exception{Method m=o.getClass().getDeclaredMethod(name,t);m.setAccessible(true);return m.invoke(o,args);}
 Object field(Object o,String name)throws Exception{Field f=o.getClass().getDeclaredField(name);f.setAccessible(true);return f.get(o);}
 Object create(String name)throws Exception{Constructor<?> ctor=Class.forName(c.getPackageName()+"."+name,true,c.getClassLoader()).getDeclaredConstructor(Context.class);ctor.setAccessible(true);return ctor.newInstance(c);}
 String strings(){StringBuilder b=new StringBuilder();runOnMainSync(()->collect(a.getWindow().getDecorView(),b));return b.toString();}
 void collect(View v,StringBuilder b){if(v instanceof TextView)b.append(((TextView)v).getText()).append('\n');if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)collect(g.getChildAt(i),b);}}
 TextView find(View v,String value){if(v instanceof TextView&&value.equals(((TextView)v).getText().toString()))return(TextView)v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){TextView f=find(g.getChildAt(i),value);if(f!=null)return f;}}return null;}
 void click(String value){final TextView[] t=new TextView[1];runOnMainSync(()->t[0]=find(a.getWindow().getDecorView(),value));check(t[0]!=null,"can locate "+value);runOnMainSync(()->{if(t[0].hasOnClickListeners()){t[0].performClick();return;}ViewParent p=t[0].getParent();if(p instanceof View)((View)p).performClick();else t[0].performClick();});waitForIdleSync();SystemClock.sleep(250);}
 void shot(String n)throws Exception{Bitmap b=getUiAutomation().takeScreenshot();if(b!=null)try(OutputStream o=new FileOutputStream(new File(c.getFilesDir(),"ui-"+n+".png"))){b.compress(Bitmap.CompressFormat.PNG,100,o);}}
 @SuppressWarnings({"unchecked","rawtypes"}) public void onStart(){Bundle b=new Bundle();try{
  c=getTargetContext();SharedPreferences prefs=c.getSharedPreferences("bichen",0);prefs.edit().putString("appearance","light").putString("proxyBaseCore","mihomo").putString("proxyBaseMode","tproxy").putString("proxyBaseIpv6","disable").putBoolean("proxyBaseAutoOverwrite",false).commit();
  String yaml="mode: rule\nglobal-client-fingerprint: chrome\ntproxy-port: 1234\nlisteners:\n  - name: e\n    type: ebpf\n    port: 2234\nproxies: []\nproxy-groups: [{name: SELECT, type: select, proxies: [DIRECT]}]\nrules: ['MATCH,SELECT']\n";
  Class<?> coreClass=Class.forName(c.getPackageName()+".ProxyRuntimeProfile$Core",true,c.getClassLoader());Object mihomo=Enum.valueOf((Class)coreClass,"MIHOMO");Object library=create("ProxyConfigLibrary");Object entry=invoke(library,"importConfig",new Class<?>[]{coreClass,String.class,InputStream.class},mihomo,"root.yaml",new ByteArrayInputStream(yaml.getBytes("UTF-8")));Class<?> entryClass=Class.forName(c.getPackageName()+".ProxyConfigLibrary$Entry",true,c.getClassLoader());check(yaml.equals(invoke(library,"read",new Class<?>[]{entryClass},entry)),"source config remains unchanged");
  Class<?> profileClass=Class.forName(c.getPackageName()+".ProxyRuntimeProfile",true,c.getClassLoader());Method load=profileClass.getDeclaredMethod("load",SharedPreferences.class);load.setAccessible(true);Object profile=load.invoke(null,prefs);Object manager=create("RootProxyManager");Object prepared=invoke(manager,"prepare",new Class<?>[]{profileClass},profile);String startup=(String)field(prepared,"startup");check(!startup.contains("type: ebpf")&&!startup.contains("global-client-fingerprint:"),"TPROXY runtime isolates conflicting source features even with overwrite off");check(startup.contains("external-controller: 127.0.0.1:19090")&&startup.contains("secret: '"),"private Clash API is injected for panel control");
  for(String appearance:new String[]{"light","dark"}){
   prefs.edit().putString("appearance",appearance).commit();a=startActivitySync(new Intent(c,Class.forName(c.getPackageName()+".ProxyActivity",true,c.getClassLoader())).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();SystemClock.sleep(500);String home=strings();
   check(home.contains("当前策略")&&home.contains("节点选择")&&home.contains("连接活动"),appearance+": BoxProxy-style home actions visible");check(home.contains("首页")&&home.contains("面板")&&home.contains("工具")&&home.contains("设置"),appearance+": home-panel-tools-settings navigation visible");
   click("面板");String panel=strings();check(panel.contains("策略组")&&panel.contains("来自 Mihomo 实际 Clash API"),appearance+": real strategy panel visible");click("连接");String conn=strings();check(conn.contains("Mihomo 实时连接 API")&&conn.contains("清空连接"),appearance+": panel connections tab visible");
   click("工具");String tools=strings();check(tools.contains("运行日志")&&tools.contains("最终启动配置")&&tools.contains("核心与配置"),appearance+": tools hierarchy visible");
   click("设置");String settings=strings();check(settings.contains("基础代理配置")&&settings.contains("进入基础代理配置"),appearance+": settings hierarchy visible");shot(appearance+"-boxproxy-shell");runOnMainSync(()->a.finish());waitForIdleSync();SystemClock.sleep(180);
   a=startActivitySync(new Intent(c,Class.forName(c.getPackageName()+".RootTproxyActivity",true,c.getClassLoader())).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();SystemClock.sleep(350);String basic=strings();check(basic.contains("基础代理配置")&&basic.contains("核心选择")&&basic.contains("运行模式")&&basic.contains("IPv6")&&basic.contains("自动覆写"),appearance+": basic proxy rows match reference hierarchy");check(basic.contains("查看启动配置")&&basic.contains("配置选择")&&basic.contains("root.yaml"),appearance+": startup and visible config list match BoxProxy hierarchy");check(!basic.contains("启动代理")&&!basic.contains("运行日志")&&!basic.contains("核心管理"),appearance+": service controls stay off basic settings page");shot(appearance+"-basic-proxy-config");runOnMainSync(()->a.finish());waitForIdleSync();SystemClock.sleep(180);
  }
  prefs.edit().putString("appearance","system").commit();b.putString("stream",output+"BICHEN_PROXY_UI_PASS checks="+checks+"\nBoxProxy-style shell, panel, tools, settings and basic proxy configuration verified.\n");finish(Activity.RESULT_OK,b);
 }catch(Throwable e){b.putString("stream",output+"BICHEN_PROXY_UI_FAIL\n"+android.util.Log.getStackTraceString(e));finish(Activity.RESULT_CANCELED,b);}}
 public void onCreate(Bundle args){super.onCreate(args);start();}
}